# Generated by Django 6.0.7 on 2026-07-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Contact number shown on the detail page', max_length=30),
        ),
    ]
